apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: simple-webhook-pods
webhooks:
  - name: simple-webhook.kube-system.svc # 这里必须是域名，和svc保持一致
    clientConfig:
      # 如果是本地调试使用则不适用service，这里直接使用url（# 本地运行时的URL）
      url: https://192.168.193.11:8443/mutate
      # service:
      #   name: simple-webhook
      #   namespace: kube-system
      #   path: /mutate
      #caBundle: $(cat certs/tls.crt | base64 | tr -d '\n')
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURoVENDQW0yZ0F3SUJBZ0lKQUwzQ2Y5Q2sxQjYzTUEwR0NTcUdTSWIzRFFFQkN3VUFNRzB4Q3pBSkJnTlYKQkFZVEFsVlRNUk13RVFZRFZRUUlEQXBEWVd4cFptOXlibWxoTVJZd0ZBWURWUVFIREExVFlXNGdSbkpoYm1OcApjMk52TVJNd0VRWURWUVFLREFwTmVTQkRiMjF3WVc1NU1Sd3dHZ1lEVlFRRERCTjNaV0pvYjI5ckxtUmxabUYxCmJIUXVjM1pqTUI0WERUSTBNRFl3TmpBeU5Ea3pOMW9YRFRJMU1EWXdOakF5TkRrek4xb3diVEVMTUFrR0ExVUUKQmhNQ1ZWTXhFekFSQmdOVkJBZ01Da05oYkdsbWIzSnVhV0V4RmpBVUJnTlZCQWNNRFZOaGJpQkdjbUZ1WTJsegpZMjh4RXpBUkJnTlZCQW9NQ2sxNUlFTnZiWEJoYm5reEhEQWFCZ05WQkFNTUUzZGxZbWh2YjJzdVpHVm1ZWFZzCmRDNXpkbU13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzNrM3Z0bTRtektwUk8KWlE3MCtrZTUvTUxKVVBXbFd5OE9EN2J0OGNkR3FvbEhmTWFhTFd3SkV6aDVQWlVBTXNNUGtuWFpVbDZYeHlqaQpHNlJZR3FCdnZVbWQxS3RwdmNTVTdWT3dLcTQ2aVNkejJrVG90VHExd1RrcEwyNStUaytraVJkOGM5WmJYQmt6Cm9BMEN1THNBZUZ1b3NST1B4MzFpWDZlVUdFcnpOUEVseG52WWg4NWxCMWxBSklPMDFySk9mYkQ4MkNNOWtaUWYKUDg1RFdWWjZqMFd1NjRXNmo5Wjc1U3lsRGNWRldhV2tYUVl4VTNBVG44TjFQblVvSW5uTDdGOUV5cGcvNGhONwphcE5FaEdncDFmMFgyd21EVHBZdG1GTG11MDVzWUUrVGpxTCt2ZEE0ejdTYWd5MnVVdzlMN3ZIV2lIVXJTS2NyCndFK21oWmR6QWdNQkFBR2pLREFtTUNRR0ExVWRFUVFkTUJ1SEJNQ293UXVDRTNkbFltaHZiMnN1WkdWbVlYVnMKZEM1emRtTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBTGJXemIvYVJpNm5TaUxVdWRHdThabEQ0K2lYMnhsVQpWQk13N3ROemNISC9rUzR0YXVmU0FDeHZRSlQybGJtN05GUEkvN0Qybk5HRG9wNi9PbG54NldPemFUY3VsaDdHCkt5ZHRvOXhkMjFtYmZtU0dsSGRpN2s1SFcyMEJUdTBNTzdUNm5TOVdrUFljdCtNeEZjNWVpR3MrckpNZE5RWXUKa3JWQy9pZ2E1ZTlJa0tMUC85cGs3Y1NDRWF3SDMvY0thK3RvMk5VVUdITmVKUHUySXB5QnNiMXVneXpVSzJ2TwpPZDc4NW1rV3I0WlBFeTBoWUdaVEd0Q256Z1ArQTROQkZMb3NRY1N2aGRXYmoyak12ZmV0Y01JUnFPZi9nQXpDCnhYUm5VSkwzYzh0T0xSR00xdk80UFoxNk1LbVhBai80OE1nSHRZTXRUYllCR3lLYkZNYlUvVzQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
