---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: simple-webhook
webhooks:
  - name: simple-webhook-namespace.kube-system.svc
    clientConfig:
      # 如果是本地调试使用则不适用service，这里直接使用url（# 本地运行时的URL）
      # url: https://192.168.193.11:8443/validate
      service:
        name: simple-webhook
        namespace: kube-system
        path: /validate-namespace
      # caBundle: $(cat certs/tls.crt | base64 | tr -d '\n')
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURWRENDQWp5Z0F3SUJBZ0lKQU9DcThSRGhOc1Y3TUEwR0NTcUdTSWIzRFFFQkN3VUFNRTh4Q3pBSkJnTlYKQkFZVEFsVlRNUk13RVFZRFZRUUlEQXBEWVd4cFptOXlibWxoTVJZd0ZBWURWUVFIREExVFlXNGdSbkpoYm1OcApjMk52TVJNd0VRWURWUVFLREFwTmVTQkRiMjF3WVc1NU1CNFhEVEkwTURZd05qQTVNakF3T0ZvWERUSTFNRFl3Ck5qQTVNakF3T0Zvd1R6RUxNQWtHQTFVRUJoTUNWVk14RXpBUkJnTlZCQWdNQ2tOaGJHbG1iM0p1YVdFeEZqQVUKQmdOVkJBY01EVk5oYmlCR2NtRnVZMmx6WTI4eEV6QVJCZ05WQkFvTUNrMTVJRU52YlhCaGJua3dnZ0VpTUEwRwpDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRE9NOXhqei9kTzFtL3IxUHRIM3pPMkplYVZsVmhsClMraEtoazdhN1lhYXQybW1OLzdqMThYY2tFMnYxVkNEU0VhMTJYWjlaRlFqSEhsY2tWalVmUG54ZDVOczN5aVoKdWVRZDNNOTRMWHZaeHR6MEpkUWhBZDNzRWJLVk8xaUJVSkVvTVpvcDlEL3doMzZ1N1d0bTFxdzl2S3QycjBiUQp3UU12b0pIVXVJOGMvdmZZODlyS2N4Z2dYRFlVL0VQTEtsRmN3RU9QRUE5ZzU2dTZGYVJ6TEptVVdyK2dNa205Cm9lZlI4QjVoZ3lBTmY1RjF5R1plaE42SlVrcjkwUE0zMkNIMTdtMXhJa0MrNlVxdi9xbTdXRi9FMkhjcHhORHYKelI3WEdFRlhwbkFxb25IZGVkYjMzZjVRM1F1aXJZRXJrMTRuVjhNWWVpRndIMGRBMzJoUUhJejNBZ01CQUFHagpNekF4TUM4R0ExVWRFUVFvTUNhSEJNQ293UXVDSG5OcGJYQnNaUzEzWldKb2IyOXJMbXQxWW1VdGMzbHpkR1Z0CkxuTjJZekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBbGtDSkhtbG1NUlVCQS9Qak8zNlBYRzNFQjR6clNzWGEKbWM5dWhiNnNtRDAxd1czaGJFWDJqcVVtaTJpcm56R3BFOUYvTDFLaGMzdmh4aUI1TGZqbzVWMkVubWlsU0kyMAowcWFDWUF3UktpbUJ3bEJmQkoxYkJlcWFoVVVtSFJsUVFIelREQ1VCbzd3eG1kNldNSHowa0xVemc0NWRtbjJUCjI3TVVzenNkWlM0RitmQ2RWMGFJOVRiMks3UDZCbmlmY0U4bDZFN2JaeVhnVjdFeHhvNncyMGFFb2NCOEY2bTQKeXpyeEVzb2tHR29qTko0bWp1T3greVR4ZDFBV0E1a1g5M2dBQ1UwSCtIVEZpMlQxQmJYbnovdWdETU1VVWc0ZgpXM1B1S1JHRnF5SWVld2l3UHNtbEZmMjVVQW1PS0hXQ3dNbTJuQWlTS3hrUUdtT2p1ZlJjS1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      # - operations: ["CREATE", "UPDATE"]
      - operations: ["UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["namespaces"]
    admissionReviewVersions: ["v1"]
    sideEffects: None

# ---
# apiVersion: admissionregistration.k8s.io/v1
# kind: ValidatingWebhookConfiguration
# metadata:
#   name: simple-webhook
# webhooks:
  - name: simple-webhookd-deployments.kube-system.svc    # name 必须唯一，以确保 Kubernetes 能够正确地识别和处理每个 webhook 配置。这个 name 不需要与服务的域名保持一致，但它应该是描述性的，便于管理和排错。
    clientConfig:
      # 如果是本地调试使用则不适用service，这里直接使用url（# 本地运行时的URL）
      # url: https://192.168.193.11:8443/validateDeploy
      service:
        name: simple-webhook    # clientConfig.service.name: 与服务名称匹配。
        namespace: kube-system  # clientConfig.service.namespace: 与服务所在的命名空间匹配。
        path: /validate-deploy  # 与服务代码中的路由匹配。
      # caBundle: $(cat certs/tls.crt | base64 | tr -d '\n')
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURWRENDQWp5Z0F3SUJBZ0lKQU9DcThSRGhOc1Y3TUEwR0NTcUdTSWIzRFFFQkN3VUFNRTh4Q3pBSkJnTlYKQkFZVEFsVlRNUk13RVFZRFZRUUlEQXBEWVd4cFptOXlibWxoTVJZd0ZBWURWUVFIREExVFlXNGdSbkpoYm1OcApjMk52TVJNd0VRWURWUVFLREFwTmVTQkRiMjF3WVc1NU1CNFhEVEkwTURZd05qQTVNakF3T0ZvWERUSTFNRFl3Ck5qQTVNakF3T0Zvd1R6RUxNQWtHQTFVRUJoTUNWVk14RXpBUkJnTlZCQWdNQ2tOaGJHbG1iM0p1YVdFeEZqQVUKQmdOVkJBY01EVk5oYmlCR2NtRnVZMmx6WTI4eEV6QVJCZ05WQkFvTUNrMTVJRU52YlhCaGJua3dnZ0VpTUEwRwpDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRE9NOXhqei9kTzFtL3IxUHRIM3pPMkplYVZsVmhsClMraEtoazdhN1lhYXQybW1OLzdqMThYY2tFMnYxVkNEU0VhMTJYWjlaRlFqSEhsY2tWalVmUG54ZDVOczN5aVoKdWVRZDNNOTRMWHZaeHR6MEpkUWhBZDNzRWJLVk8xaUJVSkVvTVpvcDlEL3doMzZ1N1d0bTFxdzl2S3QycjBiUQp3UU12b0pIVXVJOGMvdmZZODlyS2N4Z2dYRFlVL0VQTEtsRmN3RU9QRUE5ZzU2dTZGYVJ6TEptVVdyK2dNa205Cm9lZlI4QjVoZ3lBTmY1RjF5R1plaE42SlVrcjkwUE0zMkNIMTdtMXhJa0MrNlVxdi9xbTdXRi9FMkhjcHhORHYKelI3WEdFRlhwbkFxb25IZGVkYjMzZjVRM1F1aXJZRXJrMTRuVjhNWWVpRndIMGRBMzJoUUhJejNBZ01CQUFHagpNekF4TUM4R0ExVWRFUVFvTUNhSEJNQ293UXVDSG5OcGJYQnNaUzEzWldKb2IyOXJMbXQxWW1VdGMzbHpkR1Z0CkxuTjJZekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBbGtDSkhtbG1NUlVCQS9Qak8zNlBYRzNFQjR6clNzWGEKbWM5dWhiNnNtRDAxd1czaGJFWDJqcVVtaTJpcm56R3BFOUYvTDFLaGMzdmh4aUI1TGZqbzVWMkVubWlsU0kyMAowcWFDWUF3UktpbUJ3bEJmQkoxYkJlcWFoVVVtSFJsUVFIelREQ1VCbzd3eG1kNldNSHowa0xVemc0NWRtbjJUCjI3TVVzenNkWlM0RitmQ2RWMGFJOVRiMks3UDZCbmlmY0U4bDZFN2JaeVhnVjdFeHhvNncyMGFFb2NCOEY2bTQKeXpyeEVzb2tHR29qTko0bWp1T3greVR4ZDFBV0E1a1g5M2dBQ1UwSCtIVEZpMlQxQmJYbnovdWdETU1VVWc0ZgpXM1B1S1JHRnF5SWVld2l3UHNtbEZmMjVVQW1PS0hXQ3dNbTJuQWlTS3hrUUdtT2p1ZlJjS1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      # - operations: ["CREATE", "UPDATE"]
      - operations: ["DELETE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
