apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: default
spec:
  ports:
    - port: 443
      targetPort: 8443
      nodePort: 30000 # 使用 NodePort 暴露服务
  selector:
    app: simple-webhook
  type: NodePort
