apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webhook
  namespace: kube-system
  labels:
    app: simple-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-webhook
  template:
    metadata:
      labels:
        app: simple-webhook
    spec:
      serviceAccountName: simple-webhook
      serviceAccount: simple-webhook
      containers:
      - name: webhook
        # image: geray/simple-webhook:v1
        image: repos.cloud.cmft/ruoyi/simple-webhook:v2.1
        args:
          - '--validation-namespace-enable=true'
          - '--validation-deployment-enable=true'
          - '--tlsCertFile=/etc/webhook/certs/tls.crt'
          - '--tlsKeyFile=/etc/webhook/certs/tls.key'
          - >-
            --labels=nci.yunshan.net/vpc,kubesphere.io/workspace,kubesphere.io/namespace,ts/aaa
        ports:
          - name: http-8443
            containerPort: 8443
            protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: simple-webhook-certs
          mountPath: /etc/webhook/certs
          readOnly: true
      volumes:
      - name: simple-webhook-certs
        secret:
          secretName: simple-webhook-certs
---
apiVersion: v1
kind: Service
metadata:
  name: simple-webhook
  namespace: kube-system
  labels:
    app: simple-webhook
spec:
  selector:
    app: simple-webhook
  ports:
  - port: 443
    targetPort: 8443
