---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: simple-webhook
  labels:
    app: simple-webhook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simple-webhook
  labels:
    app: simple-webhook
rules:
- apiGroups: ["gateway.kubesphere.io"]
  resources: ["gateways"]
  verbs: ["get", "list"]

---
# clusterrole的gateway资源权限绑定到kube-system的default的sa
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gateway-access-binding
  labels:
    app: simple-webhook
subjects:
- kind: ServiceAccount
  name: simple-webhook
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: simple-webhook
  apiGroup: rbac.authorization.k8s.io
